galaxy_info:
  author: Alvaro Aleman
  description: A role to idempotently configure neutron networks, subnets and routers on a per project basis
  license: AGPLv3
  min_ansible_version: 2.0
  platforms:
  - name: EL
    versions:
    - all
  - name: GenericUNIX
    versions:
    - all
    - any
  - name: Solaris
    versions:
    - all
  - name: Fedora
    versions:
    - all
  - name: opensuse
    versions:
    - all
  - name: Amazon
    versions:
    - all
  - name: GenericBSD
    versions:
    - all
    - any
  - name: FreeBSD
    versions:
    - all
  - name: Ubuntu
    versions:
    - all
  - name: SLES
    versions:
    - all
  - name: GenericLinux
    versions:
    - all
    - any
  - name: Debian
    versions:
    - all
  galaxy_tags:
    - openstack
    - neutron

dependencies: []
