---
- hosts: all
  become: true
  vars:
    openstack_master_address: "{{ ansible_default_ipv4.address }}"
  pre_tasks:
    - name: Set environment
      with_items:
        - LANG=en_US.utf-8
        - LC_ALL=en_US.utf-8
      lineinfile:
        dest: /etc/environment
        line: "{{ item }}"
    - name: Stop and disable networkmanager
      service:
        name: NetworkManager
        state: stopped
        enabled: false
    - name: Install release package
      yum:
        name: centos-release-openstack-pike
    - name: Update all package
      yum:
        name: '*'
        state: latest
    - name: Install packstack
      yum:
        name: openstack-packstack
    - name: Create volume group
      shell: >
        pvcreate /dev/vdb &&
        vgcreate cinder-volumes /dev/vdb &&
        touch /var/vg-created
      args:
        creates: /var/vg-created
    - name: Deploy answerfile
      register: registered_answerfile
      template:
        src: answerfile.j2
        dest: /root/answerfile
    - name: Execute packstack
      when: registered_answerfile|changed
      command: packstack --answer-file=/root/answerfile
      args:
        creates: /root/keystonerc_admin
    - name: Install shade
      yum:
        name: python2-shade
  roles:
    - openstack.projects
    - openstack.neutron-networks
  tasks:
    - name: Create cirros image
      shell: >
        cd /root &&
        source /root/keystonerc_admin &&
        curl -LO https://download.cirros-cloud.net/0.3.5/cirros-0.3.5-x86_64-disk.img &&
        openstack image create --disk-format=qcow2 --shared --file cirros-0.3.5-x86_64-disk.img cirros-035
      args:
        creates: /root/cirros-0.3.5-x86_64-disk.img
